"""
Target-aware AAIS specialization layer.

Sits between a QSystem target and the solver. Instead of handing the solver
the fully general machine (all-pairs ZZ lines, all-pairs dressing terms, free
atom positions), it inspects the target Hamiltonian's interaction graph and
produces a SpecPlan that:

  1. synthesizes a concrete geometry for the interaction graph (currently 1D
     chains) and freezes atom positions to constants,
  2. prunes derived ZZ signal lines to the bonds actually present,
  3. truncates the dressing sum to pairs within a shell cutoff, with the
     dropped 1/R^6 tail reported as an explicit error bound,
  4. computes an analytic warm start (dressing amplitude, compensating
     detunings, Rabi amplitudes) written into the machine's variable inits.

The machine is still generated by the AAIS (rydberg2d.generate_qmachine);
the plan only chooses its optional parameters and initial values, so the
device model has a single source of truth.

Machine size goes from O(n^2) instructions to O(n), and with positions frozen
the solve has O(n) variables and O(n) equations.
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

import numpy as np


@dataclass
class SpecPlan:
    n: int
    positions: List[Tuple[float, float]]        # per qubit, qubit 0 at origin
    links: List[Tuple[int, int]]                # derived ZZ lines to expose
    dressing_pairs: List[Tuple[int, int]]       # pairs kept in the dressing sum
    R: float                                    # nearest-neighbor spacing (μm)
    theta: float                                # uniform ZZ coupling of the target
    dressing_init: float                        # warm start: dressing amplitude o
    detuning_init: Dict[int, float]             # warm start: d_i per site
    rabi_init: Dict[int, Tuple[float, float]]   # warm start: (Ω_i, φ_i) per site
    dropped_zz_l1: float                        # Σ|J_ij|/4 over truncated pairs
    report: dict = field(default_factory=dict)

    @property
    def flat_positions(self) -> List[float]:
        """sol_gvars-equivalent layout [x1, y1, x2, y2, ...] (qubit 0 implicit)."""
        return [c for (x, y) in self.positions[1:] for c in (x, y)]


def extract_target(h, num_sites):
    """Decompose a TIHamiltonian into 1-body Pauli coefficients and ZZ bonds.

    Returns (singles, bonds):
      singles : {site: {"X": c, "Y": c, "Z": c}}
      bonds   : {(i, j): c}  with i < j, from Z_iZ_j terms
    Raises NotImplementedError for terms outside span{X, Y, Z, ZZ}.
    """
    singles = {i: {"X": 0.0, "Y": 0.0, "Z": 0.0} for i in range(num_sites)}
    bonds = {}
    for prod, c in h.ham:
        active = [(k, op) for k, op in prod.d.items() if op != ""]
        if len(active) == 0:
            continue  # identity — global phase, no equation is built for it
        if isinstance(c, complex):
            if abs(c.imag) > 1e-9:
                raise NotImplementedError("Complex coefficients not supported.")
            c = c.real
        c = float(c)
        if len(active) == 1:
            site, op = active[0]
            if op not in ("X", "Y", "Z"):
                raise NotImplementedError(f"Unsupported 1-body operator {op!r}.")
            singles[site][op] += c
        elif len(active) == 2:
            (s0, op0), (s1, op1) = active
            if op0 != "Z" or op1 != "Z":
                raise NotImplementedError(
                    f"Unsupported 2-body term {op0}{op1} on ({s0},{s1}).")
            key = (min(s0, s1), max(s0, s1))
            bonds[key] = bonds.get(key, 0.0) + c
        else:
            raise NotImplementedError(
                f"{len(active)}-body target terms are not supported.")
    return singles, bonds


def _order_path(bonds, sites):
    """Order `sites` along the path graph defined by `bonds`.

    Returns the site ordering, or raises NotImplementedError if the bond graph
    on these sites is not a simple path (cycles, branches, disconnection).
    """
    adj = {s: [] for s in sites}
    for a, b in bonds:
        adj[a].append(b)
        adj[b].append(a)
    degs = {s: len(v) for s, v in adj.items()}
    if any(d > 2 for d in degs.values()):
        raise NotImplementedError(
            "Interaction graph has a site with degree > 2 — only 1D chains "
            "are supported by the specializer so far.")
    ends = [s for s, d in degs.items() if d == 1]
    if len(ends) != 2 or len(bonds) != len(sites) - 1:
        raise NotImplementedError(
            "Interaction graph is not a single open chain (cycle, or "
            "multiple components among coupled sites).")
    order = [min(ends)]
    prev = None
    while len(order) < len(sites):
        nxts = [s for s in adj[order[-1]] if s != prev]
        if len(nxts) != 1:
            raise NotImplementedError("Interaction graph is not a simple path.")
        prev = order[-1]
        order.append(nxts[0])
    return order


def make_plan(qs, C_6, shells=1, park_base=(1000.0, 1000.0), park_spacing=5.0,
              uniform_rtol=1e-6):
    """Build a SpecPlan for a QSystem whose coupled sites form a 1D chain.

    The plan is derived from the union of bonds over all evolution segments;
    warm-start coefficients come from segment 0 (the evolution Hamiltonian —
    later segments of PSR H_lists are kicks the solver refines from there).

    C_6 is passed in (rather than imported) so the plan stays consistent with
    the AAIS module that will consume it.
    """
    n = qs.num_sites

    all_bonds = set()
    for h, _t in qs.evos:
        _, b = extract_target(h, n)
        all_bonds.update(b.keys())
    singles0, bonds0 = extract_target(qs.evos[0][0], n)

    if not all_bonds:
        raise NotImplementedError("Target has no ZZ bonds — nothing to specialize.")

    thetas = [bonds0[b] for b in sorted(bonds0)]
    theta = float(np.mean(thetas)) if thetas else 0.0
    if thetas and (np.max(thetas) - np.min(thetas)) > uniform_rtol * max(
            1e-12, abs(theta)):
        raise NotImplementedError(
            "Non-uniform ZZ couplings — the global dressing line can only "
            "realize a uniform coupling; per-bond specialization is not "
            "implemented yet.")
    if theta == 0.0:
        raise NotImplementedError("Evolution segment has no ZZ coupling.")

    # Spacing chosen so the dressing amplitude warm-starts at |o| = 1:
    # theta = o * C6 / (4 R^6).
    R = (C_6 / (4.0 * abs(theta))) ** (1.0 / 6.0)
    o_init = float(np.sign(theta))

    coupled = sorted({s for b in all_bonds for s in b})
    order = _order_path(all_bonds, coupled)

    positions = [None] * n
    for k, site in enumerate(order):
        positions[site] = (k * R, 0.0)
    n_parked = 0
    for i in range(n):
        if positions[i] is None:
            positions[i] = (park_base[0], park_base[1] + park_spacing * n_parked)
            n_parked += 1
    # rydberg2d fixes qubit 0 at the origin — translate so it is.
    x0, y0 = positions[0]
    positions = [(x - x0, y - y0) for (x, y) in positions]

    # Dressing pairs: everything within `shells` chain spacings (plus slack).
    cutoff = shells * R * 1.001
    kept, dropped_l1 = [], 0.0
    for i in range(n):
        for j in range(i):
            d2 = (positions[i][0] - positions[j][0]) ** 2 + \
                 (positions[i][1] - positions[j][1]) ** 2
            Jij4 = abs(o_init) * C_6 / (4.0 * d2 ** 3)
            if d2 <= cutoff * cutoff:
                kept.append((j, i))
            else:
                dropped_l1 += Jij4

    links = sorted(all_bonds)

    # Warm start. Dressing pair (i,j) contributes theta_ij*(Z_iZ_j - Z_i - Z_j + I)
    # with theta_ij = o*C6/(4 d_ij^6); detuning -d_i*(I-Z_i)/2 contributes +d_i/2
    # to Z_i. Solve d_i/2 - Σ_j theta_ij = c_z(i).
    theta_sum = {i: 0.0 for i in range(n)}
    for j, i in kept:
        d2 = (positions[i][0] - positions[j][0]) ** 2 + \
             (positions[i][1] - positions[j][1]) ** 2
        th = o_init * C_6 / (4.0 * d2 ** 3)
        theta_sum[i] += th
        theta_sum[j] += th
    detuning_init = {
        i: 2.0 * singles0[i]["Z"] + 2.0 * theta_sum[i] for i in range(n)
    }
    # Rabi Ω/2 (cosφ X − sinφ Y) = hx X + hy Y.
    rabi_init = {}
    for i in range(n):
        hx, hy = singles0[i]["X"], singles0[i]["Y"]
        omega = 2.0 * float(np.hypot(hx, hy))
        # sign folded into φ by atan2; amplitude stays ≥ 0
        phi = float(np.arctan2(-hy, hx)) if omega > 0 else 0.0
        rabi_init[i] = (omega, phi)

    return SpecPlan(
        n=n,
        positions=positions,
        links=links,
        dressing_pairs=kept,
        R=R,
        theta=theta,
        dressing_init=o_init,
        detuning_init=detuning_init,
        rabi_init=rabi_init,
        dropped_zz_l1=dropped_l1,
        report=dict(
            n=n, bonds=len(links), dressing_pairs=len(kept),
            shells=shells, R_um=R, theta=theta,
            dropped_zz_l1=dropped_l1,
            dropped_rel=dropped_l1 / (abs(theta) * max(len(links), 1)),
            parked_sites=n_parked,
        ),
    )


def _classify(name):
    if name.startswith("Detuning of site"):
        return ("detuning", int(name.split()[-1]))
    if name.startswith("Rabi of site"):
        return ("rabi", int(name.split()[-1]))
    if "dressing" in name.lower():
        return ("dressing",)
    if name.startswith("c") and name.endswith("_zz"):
        return ("zz",)
    return ("unknown",)


def apply_warm_start(mach, plan):
    """Write the plan's analytic initial values into the machine's lvars.

    The solver's build_obj reads lvar.init_value, so this is the entire
    warm-start plumbing. ZZ lines start at 0 (the dressing carries the
    evolution coupling; ZZ lines exist for kick segments).
    """
    for line in mach.lines:
        for ins in line.inss:
            cls = _classify(ins.name)
            if cls[0] == "detuning":
                ins.lvars[0].init_value = plan.detuning_init.get(cls[1], 0.0)
            elif cls[0] == "rabi":
                omega, phi = plan.rabi_init.get(cls[1], (0.0, 0.0))
                ins.lvars[0].init_value = omega
                ins.lvars[1].init_value = phi
            elif cls[0] == "dressing":
                ins.lvars[0].init_value = plan.dressing_init
            elif cls[0] == "zz":
                ins.lvars[0].init_value = 0.0
